import unittest
from task03 import simulate_random_walk


class TestSimulateRandomWalk(unittest.TestCase):
    def test_when_seed_is_123_walk_100_times_then_steps_matches_expected_value(self):
        steps = simulate_random_walk(100)
        expected_values = [
            0,
            0,
            1,
            2,
            1,
            3,
            2,
            1,
            2,
            1,
            2,
            3,
            4,
            7,
            6,
            7,
            8,
            14,
            13,
            14,
            13,
            12,
            11,
            12,
            13,
            12,
            13,
            14,
            13,
            14,
            15,
            20,
            19,
            24,
            23,
            24,
            25,
            24,
            23,
            22,
            21,
            22,
            21,
            22,
            23,
            22,
            23,
            22,
            21,
            22,
            21,
            22,
            21,
            23,
            24,
            25,
            29,
            32,
            31,
            30,
            32,
            33,
            34,
            33,
            34,
            35,
            36,
            42,
            41,
            42,
            43,
            44,
            43,
            44,
            45,
            47,
            48,
            49,
            51,
            52,
            51,
            52,
            51,
            52,
            51,
            52,
            53,
            54,
            55,
            56,
            55,
            54,
            55,
            54,
            55,
            56,
            57,
            58,
            57,
            58,
            59,
        ]
        self.assertEqual(steps, expected_values)


if __name__ == "__main__":
    unittest.main()
