import unittest
from task02 import simulate_random_walk


class TestSimulateRandomWalk(unittest.TestCase):
    def test_when_seed_is_123_walk_100_times_then_steps_matches_expected_value(self):
        steps = simulate_random_walk(100)
        expected_values = [
            0,
            -1,
            0,
            1,
            0,
            2,
            1,
            0,
            1,
            0,
            1,
            2,
            3,
            6,
            5,
            6,
            7,
            13,
            12,
            13,
            12,
            11,
            10,
            11,
            12,
            11,
            12,
            13,
            12,
            13,
            14,
            19,
            18,
            23,
            22,
            23,
            24,
            23,
            22,
            21,
            20,
            21,
            20,
            21,
            22,
            21,
            22,
            21,
            20,
            21,
            20,
            21,
            20,
            22,
            23,
            24,
            28,
            31,
            30,
            29,
            31,
            32,
            33,
            32,
            33,
            34,
            35,
            41,
            40,
            41,
            42,
            43,
            42,
            43,
            44,
            46,
            47,
            48,
            50,
            51,
            50,
            51,
            50,
            51,
            50,
            51,
            52,
            53,
            54,
            55,
            54,
            53,
            54,
            53,
            54,
            55,
            56,
            57,
            56,
            57,
            58,
        ]
        self.assertEqual(steps, expected_values)


if __name__ == "__main__":
    unittest.main()
